/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameState {
  'totalScores' : Array<bigint>,
  'currentPlayer' : bigint,
  'isOver' : boolean,
  'remainingScores' : Array<bigint>,
}
export interface GameView {
  'id' : Id,
  'playerIds' : Array<Id>,
  'totalScores' : Array<bigint>,
  'turns' : Array<TurnResult>,
  'currentPlayer' : bigint,
  'isOver' : boolean,
  'remainingScores' : Array<bigint>,
  'throws' : Array<ThrowResult>,
}
export type HttpBody = Uint8Array;
export type HttpHeader = [string, string];
export type HttpMethod = string;
export interface HttpRequest {
  'url' : string,
  'method' : HttpMethod,
  'body' : HttpBody,
  'headers' : Array<HttpHeader>,
}
export interface HttpResponse {
  'body' : HttpBody,
  'headers' : Array<HttpHeader>,
  'status_code' : HttpStatusCode,
}
export type HttpStatusCode = number;
export type Id = bigint;
export interface Player { 'id' : Id, 'name' : string }
export interface ThrowResult { 'multiplier' : bigint, 'score' : bigint }
export interface TurnResult { 'throws' : Array<ThrowResult> }
export interface _SERVICE {
  'createGame' : ActorMethod<[Array<Id>], GameView>,
  'createPlayer' : ActorMethod<[string], Player>,
  'getAllGames' : ActorMethod<[], Array<GameView>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getGameState' : ActorMethod<[Id], GameState>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'recordThrow' : ActorMethod<[Id, bigint, bigint], ThrowResult>,
  'recordTurn' : ActorMethod<[Id, Array<ThrowResult>], TurnResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];