/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const ThrowResult = IDL.Record({
  'multiplier' : IDL.Nat,
  'score' : IDL.Nat,
});
export const TurnResult = IDL.Record({ 'throws' : IDL.Vec(ThrowResult) });
export const GameView = IDL.Record({
  'id' : Id,
  'playerIds' : IDL.Vec(Id),
  'totalScores' : IDL.Vec(IDL.Nat),
  'turns' : IDL.Vec(TurnResult),
  'currentPlayer' : IDL.Nat,
  'isOver' : IDL.Bool,
  'remainingScores' : IDL.Vec(IDL.Nat),
  'throws' : IDL.Vec(ThrowResult),
});
export const Player = IDL.Record({ 'id' : Id, 'name' : IDL.Text });
export const GameState = IDL.Record({
  'totalScores' : IDL.Vec(IDL.Nat),
  'currentPlayer' : IDL.Nat,
  'isOver' : IDL.Bool,
  'remainingScores' : IDL.Vec(IDL.Nat),
});
export const HttpMethod = IDL.Text;
export const HttpBody = IDL.Vec(IDL.Nat8);
export const HttpHeader = IDL.Tuple(IDL.Text, IDL.Text);
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : HttpMethod,
  'body' : HttpBody,
  'headers' : IDL.Vec(HttpHeader),
});
export const HttpStatusCode = IDL.Nat16;
export const HttpResponse = IDL.Record({
  'body' : HttpBody,
  'headers' : IDL.Vec(HttpHeader),
  'status_code' : HttpStatusCode,
});

export const idlService = IDL.Service({
  'createGame' : IDL.Func([IDL.Vec(Id)], [GameView], []),
  'createPlayer' : IDL.Func([IDL.Text], [Player], []),
  'getAllGames' : IDL.Func([], [IDL.Vec(GameView)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getGameState' : IDL.Func([Id], [GameState], ['query']),
  'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'recordThrow' : IDL.Func([Id, IDL.Nat, IDL.Nat], [ThrowResult], []),
  'recordTurn' : IDL.Func([Id, IDL.Vec(ThrowResult)], [TurnResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const ThrowResult = IDL.Record({ 'multiplier' : IDL.Nat, 'score' : IDL.Nat });
  const TurnResult = IDL.Record({ 'throws' : IDL.Vec(ThrowResult) });
  const GameView = IDL.Record({
    'id' : Id,
    'playerIds' : IDL.Vec(Id),
    'totalScores' : IDL.Vec(IDL.Nat),
    'turns' : IDL.Vec(TurnResult),
    'currentPlayer' : IDL.Nat,
    'isOver' : IDL.Bool,
    'remainingScores' : IDL.Vec(IDL.Nat),
    'throws' : IDL.Vec(ThrowResult),
  });
  const Player = IDL.Record({ 'id' : Id, 'name' : IDL.Text });
  const GameState = IDL.Record({
    'totalScores' : IDL.Vec(IDL.Nat),
    'currentPlayer' : IDL.Nat,
    'isOver' : IDL.Bool,
    'remainingScores' : IDL.Vec(IDL.Nat),
  });
  const HttpMethod = IDL.Text;
  const HttpBody = IDL.Vec(IDL.Nat8);
  const HttpHeader = IDL.Tuple(IDL.Text, IDL.Text);
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : HttpMethod,
    'body' : HttpBody,
    'headers' : IDL.Vec(HttpHeader),
  });
  const HttpStatusCode = IDL.Nat16;
  const HttpResponse = IDL.Record({
    'body' : HttpBody,
    'headers' : IDL.Vec(HttpHeader),
    'status_code' : HttpStatusCode,
  });
  
  return IDL.Service({
    'createGame' : IDL.Func([IDL.Vec(Id)], [GameView], []),
    'createPlayer' : IDL.Func([IDL.Text], [Player], []),
    'getAllGames' : IDL.Func([], [IDL.Vec(GameView)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getGameState' : IDL.Func([Id], [GameState], ['query']),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'recordThrow' : IDL.Func([Id, IDL.Nat, IDL.Nat], [ThrowResult], []),
    'recordTurn' : IDL.Func([Id, IDL.Vec(ThrowResult)], [TurnResult], []),
  });
};

export const init = ({ IDL }) => { return []; };