/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: Id;
    name: string;
}
export interface ThrowResult {
    multiplier: bigint;
    score: bigint;
}
export interface GameView {
    id: Id;
    playerIds: Array<Id>;
    totalScores: Array<bigint>;
    turns: Array<TurnResult>;
    currentPlayer: bigint;
    isOver: boolean;
    remainingScores: Array<bigint>;
    throws: Array<ThrowResult>;
}
export type HttpMethod = string;
export interface HttpResponse {
    body: HttpBody;
    headers: Array<HttpHeader>;
    status_code: HttpStatusCode;
}
export type Id = bigint;
export type HttpBody = Uint8Array;
export interface GameState {
    totalScores: Array<bigint>;
    currentPlayer: bigint;
    isOver: boolean;
    remainingScores: Array<bigint>;
}
export interface TurnResult {
    throws: Array<ThrowResult>;
}
export interface HttpRequest {
    url: string;
    method: HttpMethod;
    body: HttpBody;
    headers: Array<HttpHeader>;
}
export type HttpHeader = [string, string];
export type HttpStatusCode = number;
export interface backendInterface {
    createGame(playerIds: Array<Id>): Promise<GameView>;
    createPlayer(name: string): Promise<Player>;
    getAllGames(): Promise<Array<GameView>>;
    getAllPlayers(): Promise<Array<Player>>;
    getGameState(gameId: Id): Promise<GameState>;
    http_request(req: HttpRequest): Promise<HttpResponse>;
    recordThrow(gameId: Id, value: bigint, multiplier: bigint): Promise<ThrowResult>;
    recordTurn(gameId: Id, throws: Array<ThrowResult>): Promise<TurnResult>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createGame(arg0: Array<Id>): Promise<GameView> {
        if (this.processError) {
            try {
                const result = await this.actor.createGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGame(arg0);
            return result;
        }
    }
    async createPlayer(arg0: string): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(arg0);
            return result;
        }
    }
    async getAllGames(): Promise<Array<GameView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGames();
            return result;
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return result;
        }
    }
    async getGameState(arg0: Id): Promise<GameState> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameState(arg0);
            return result;
        }
    }
    async http_request(arg0: HttpRequest): Promise<HttpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.http_request(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.http_request(arg0);
            return result;
        }
    }
    async recordThrow(arg0: Id, arg1: bigint, arg2: bigint): Promise<ThrowResult> {
        if (this.processError) {
            try {
                const result = await this.actor.recordThrow(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordThrow(arg0, arg1, arg2);
            return result;
        }
    }
    async recordTurn(arg0: Id, arg1: Array<ThrowResult>): Promise<TurnResult> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTurn(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTurn(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
